# Generated by Django 4.2.7 on 2024-03-03 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("DigitalZoo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Zookeeper",
            fields=[
                (
                    "staff_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="DigitalZoo.staff",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("responsibility", models.CharField(max_length=100)),
                ("qualification", models.CharField(max_length=100)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DigitalZoo.venue",
                    ),
                ),
            ],
            bases=("DigitalZoo.staff",),
        ),
        migrations.CreateModel(
            name="CareLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.IntegerField()),
                ("temperature", models.FloatField()),
                ("diet", models.CharField(max_length=100)),
                ("medicine", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DigitalZoo.animal",
                    ),
                ),
                (
                    "zookeeper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DigitalZoo.zookeeper",
                    ),
                ),
            ],
        ),
    ]
