# Generated by Django 4.2.7 on 2024-03-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("DigitalZoo", "0003_remove_zookeeper_venue"),
    ]

    operations = [
        migrations.AddField(
            model_name="zookeeper",
            name="venue",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="DigitalZoo.venue",
            ),
            preserve_default=False,
        ),
    ]
