# Generated by Django 4.2.7 on 2024-03-03 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DigitalZoo", "0004_zookeeper_venue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zookeeper",
            name="venue",
        ),
    ]
